services:
  mysql:
    image: mysql:8.0
    container_name: mysql-school
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: school_schedule
      MYSQL_USER: schooladmin
      MYSQL_PASSWORD: schoolpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - school-network

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak-school-schedule
    command: start-dev --import-realm
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-config/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - school-network
    healthcheck:
      test: [ "CMD-SHELL", "timeout 30 sh -c '</dev/tcp/localhost/8080'" ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 60s

  schoolschedule:
    build: .
    container_name: school-schedule-app
    depends_on:
      keycloak:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-school:3306/school_schedule
      SPRING_DATASOURCE_USERNAME: schooladmin
      SPRING_DATASOURCE_PASSWORD: schoolpassword
    networks:
      - school-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql-data:

networks:
  school-network:
    driver: bridge
