server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/school_schedule?useSSL=false&serverTimezone=UTC
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.platform=school_schedule
spring.datasource.username=schooladmin
spring.datasource.password=schoolpassword
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema-school_schedule.sql
spring.sql.init.data-locations=classpath:sql/data-school_schedule.sql
spring.jpa.hibernate.naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

spring.mvc.hiddenmethod.filter.enabled=true

spring.security.oauth2.client.registration.google.client-id=168316886094-08oohbd5oahjluq4m96ls8afdj9sbbfh.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
