server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://mysql-school:3306/school_schedule

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.sql.init.platform=school_schedule
spring.datasource.username=schooladmin
spring.datasource.password=schoolpassword
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.generate-ddl=false
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema-school_schedule.sql
spring.sql.init.data-locations=classpath:sql/data-school_schedule.sql
spring.jpa.hibernate.naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
spring.mvc.hiddenmethod.filter.enabled=true

# --- KEYCLOAK ---
# Keycloak issuer (????? URL)
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8081/realms/school-scheduler

# --- JWT ??? ??????-??????? ---
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/school-scheduler

# ????'??????, ?????? ???? ?? ?????????
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/school-scheduler/protocol/openid-connect/certs

#spring.security.oauth2.client.registration.spring-app.client-id=spring-app
#spring.security.oauth2.client.registration.spring-app.client-name=spring-app
#spring.security.oauth2.client.registration.spring-app.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.spring-app.redirect-uri=http://localhost:8080/login/oauth2/code/spring-app
#spring.security.oauth2.client.registration.spring-app.scope=openid

#spring.security.oauth2.client.provider.spring-app.issuer-uri=http://keycloak:8080/realms/school-scheduler

# Keycloak server URL
keycloak.auth-server-url=http://localhost:8081/
# Realm, ???? ???????????
keycloak.realm=school-scheduler
# Client ID ? Keycloak (???, ?? ????????)
keycloak.resource=spring-app
# ???? ?????? ?? ??????????????, ?? false (??? ? ?????? ??????? On = ??????????????)
keycloak.credentials.secret=pnTNV9g52eB6kQswruM4OGufQjVItyMc
# ???????? Spring Security, ??? ??????????????? Keycloak ???????
keycloak.ssl-required=external
keycloak.public-client=true
keycloak.bearer-only=false
# ?????????? ??????????? Spring Boot security (Keycloak ?? ????????)
spring.main.web-application-type=servlet
# ??? Keycloak Spring Boot Adapter
keycloak.use-resource-role-mappings=true

# Keycloak

keycloak.security-constraints[0].authRoles[0]=USER
keycloak.security-constraints[0].authRoles[1]=ADMIN

keycloak.security-constraints[0].authRoles=USER,ADMIN
keycloak.security-constraints[0].securityCollections[0].patterns=/*
keycloak.security-constraints[0].securityCollections[0].patterns[0]=/*

# Redirect URL ????? ??????
spring.security.oauth2.client.registration.keycloak.client-id=spring-app
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri=http://localhost:8080/login/oauth2/code/keycloak

spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:8081/realms/school-scheduler/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:8081/realms/school-scheduler/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:8081/realms/school-scheduler/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:8081/realms/school-scheduler/protocol/openid-connect/certs


spring.security.oauth2.client.registration.keycloak.client-secret=pnTNV9g52eB6kQswruM4OGufQjVItyMc
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

