server.port=8080
spring.datasource.url=jdbc:h2:/data/db/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=create

spring=
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "168316886094-08oohbd5oahjluq4m96ls8afdj9sbbfh.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo