INSERT INTO CLASSES (id, name) VALUES (1, '1');
INSERT INTO CLASSES (id, name) VALUES (2, '2');
INSERT INTO CLASSES (id, name) VALUES (3, '3');
INSERT INTO CLASSES (id, name) VALUES (4, '4');
INSERT INTO CLASSES (id, name) VALUES (5, '5');
INSERT INTO CLASSES (id, name) VALUES (6, '6');
INSERT INTO CLASSES (id, name) VALUES (7, '7');
INSERT INTO CLASSES (id, name) VALUES (8, '8');
INSERT INTO CLASSES (id, name) VALUES (9, '9');
INSERT INTO CLASSES (id, name) VALUES (10, '10');
INSERT INTO CLASSES (id, name) VALUES (11, '11');
INSERT INTO CLASSES (id, name) VALUES (12, '12');
INSERT INTO CLASSES (id, name) VALUES (13, 'Індивідуальне');

INSERT INTO DAY_OF_WEEK (id, name) VALUES (1, 'Понеділок');
INSERT INTO DAY_OF_WEEK (id, name) VALUES (2, 'Вівторок');
INSERT INTO DAY_OF_WEEK (id, name) VALUES (3, 'Середа');
INSERT INTO DAY_OF_WEEK (id, name) VALUES (4, 'Четвер');
INSERT INTO DAY_OF_WEEK (id, name) VALUES (5, 'П’ятниця');

INSERT INTO LESSON_TIME (id, time) VALUES (1, '09:15-10:00');
INSERT INTO LESSON_TIME (id, time) VALUES (2, '10:10-10:55');
INSERT INTO LESSON_TIME (id, time) VALUES (3, '11:05-11:50');
INSERT INTO LESSON_TIME (id, time) VALUES (4, '12:05-12:50');
INSERT INTO LESSON_TIME (id, time) VALUES (5, '13:00-13:45');
INSERT INTO LESSON_TIME (id, time) VALUES (6, '13:55-14:40');
INSERT INTO LESSON_TIME (id, time) VALUES (7, '14:50-15:35');

INSERT INTO SUBJECT (id, name) VALUES (1, 'Німецька мова');
INSERT INTO SUBJECT (id, name) VALUES (2, 'Українська мова');
INSERT INTO SUBJECT (id, name) VALUES (3, 'Українська література');
INSERT INTO SUBJECT (id, name) VALUES (4, 'Зарбужіна література');
INSERT INTO SUBJECT (id, name) VALUES (5, 'Музика');
INSERT INTO SUBJECT (id, name) VALUES (6, 'Англійська мова');
INSERT INTO SUBJECT (id, name) VALUES (7, 'Алгебра');
INSERT INTO SUBJECT (id, name) VALUES (8, 'Геометрія');
INSERT INTO SUBJECT (id, name) VALUES (9, 'Фізика');
INSERT INTO SUBJECT (id, name) VALUES (10, 'Історія України');
INSERT INTO SUBJECT (id, name) VALUES (11, 'Всесвітня історія');
INSERT INTO SUBJECT (id, name) VALUES (12, 'Основи здоров''я');
INSERT INTO SUBJECT (id, name) VALUES (13, 'Біологія');
INSERT INTO SUBJECT (id, name) VALUES (14, 'Екологія');
INSERT INTO SUBJECT (id, name) VALUES (15, 'Природознавство');
INSERT INTO SUBJECT (id, name) VALUES (16, 'Географія');
INSERT INTO SUBJECT (id, name) VALUES (17, 'Хімія');
INSERT INTO SUBJECT (id, name) VALUES (18, 'Інформатика');
INSERT INTO SUBJECT (id, name) VALUES (19, 'Технології');
INSERT INTO SUBJECT (id, name) VALUES (20, 'Медицина');
INSERT INTO SUBJECT (id, name) VALUES (21, 'Мистецтво');
INSERT INTO SUBJECT (id, name) VALUES (22, 'Фізична культура');
INSERT INTO SUBJECT (id, name) VALUES (23, 'Фінансова грамотність');
INSERT INTO SUBJECT (id, name) VALUES (24, 'Громадянська освіта');
INSERT INTO SUBJECT (id, name) VALUES (25, 'Математика');
INSERT INTO SUBJECT (id, name) VALUES (26, 'Природознавство');

INSERT INTO TEACHER (id, name) VALUES (1, 'Власенко Людмила Вікторівна');
INSERT INTO TEACHER (id, name) VALUES (2, 'Шевченко Тетяна Михайлівна');
INSERT INTO TEACHER (id, name) VALUES (3, 'Власенко Людмила Дмитрівна');
INSERT INTO TEACHER (id, name) VALUES (4, 'Кондаренко Ірина Михайлівна');
INSERT INTO TEACHER (id, name) VALUES (5, 'Гуленко Володимир Сергійович');
INSERT INTO TEACHER (id, name) VALUES (6, 'Олефіренко Ірина Леонідівна');
INSERT INTO TEACHER (id, name) VALUES (7, 'Куцукінь Володимир Микоолайович');
INSERT INTO TEACHER (id, name) VALUES (8, 'Гелевера Анатолій Андрійович');
INSERT INTO TEACHER (id, name) VALUES (9, 'Олефіренко Анатолій Сергійович');
INSERT INTO TEACHER (id, name) VALUES (10, 'Власенко Світлана Сергіївна');
INSERT INTO TEACHER (id, name) VALUES (11, 'Тесленко Людмила Миколаївна');
INSERT INTO TEACHER (id, name) VALUES (12, 'Кондаренко Олександр Андрійович');
INSERT INTO TEACHER (id, name) VALUES (13, 'Демидюк Сергій Володимирович');

INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (1, 1, 1);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (2, 2, 2);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (3, 2, 3);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (4, 3, 2);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (5, 3, 3);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (6, 3, 4);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (7, 3, 5);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (8, 4, 6);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (9, 5, 6);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (10, 6, 7);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (11, 6, 8);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (12, 7, 7);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (13, 7, 9);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (14, 8, 10);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (15, 8, 11);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (16, 8, 24);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (17, 9, 12);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (18, 9, 13);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (19, 9, 14);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (20, 9, 15);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (21, 10, 16);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (22, 10, 17);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (23, 11, 18);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (24, 11, 19);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (25, 11, 7);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (26, 11, 20);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (27, 12, 21);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (28, 12, 19);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (29, 12, 22);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (30, 12, 23);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (31, 13, 22);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (32, 6, 25);
INSERT INTO TEACHER_SUBJECT (id, teacher_id, subject_id) VALUES (33, 8, 26);

INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (1, 1, 6, 3, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (2, 1, 8, 9, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (3, 1, 10, 7, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (4, 1, 11, 13, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (5, 1, 7, 22, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (6, 1, 9, 23, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (7, 1, 5, 29, 1, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (8, 2, 7, 2, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (9, 2, 5, 8, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (10, 2, 9, 13, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (11, 2, 10, 14, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (12, 2, 11, 22, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (13, 2, 8, 23, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (14, 2, 6, 29, 1, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (15, 3, 9, 2, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (16, 3, 1, 8, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (17, 3, 6, 32, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (18, 3, 7, 13, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (19, 3, 5, 14, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (20, 3, 10, 22, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (21, 3, 11, 23, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (22, 3, 8, 31, 1, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (23, 4, 10, 2, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (24, 4, 11, 2, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (25, 4, 3, 8, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (26, 4, 5, 32, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (27, 4, 8, 13, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (28, 4, 7, 14, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (29, 4, 6, 20, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (30, 4, 9, 31, 1, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (31, 5, 6, 6, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (32, 5, 4, 8, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (33, 5, 8, 10, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (34, 5, 10, 13, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (35, 5, 9, 18, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (36, 5, 11, 24, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (37, 5, 5, 28, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (38, 5, 7, 31, 1, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (39, 6, 5, 4, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (40, 6, 11, 9, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (41, 6, 9, 10, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (42, 6, 8, 21, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (43, 6, 7, 24, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (44, 6, 6, 28, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (45, 6, 10, 31, 1, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (46, 7, 7, 6, 1, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (47, 7, 8, 18, 1, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (48, 7, 9, 24, 1, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (49, 7, 6, 28, 1, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (50, 7, 11, 31, 1, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (51, 1, 13, 2, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (52, 1, 9, 6, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (53, 1, 6, 9, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (54, 1, 5, 32, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (55, 1, 11, 14, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (56, 1, 8, 18, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (57, 1, 7, 21, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (58, 1, 10, 23, 2, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (59, 2, 7, 1, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (60, 2, 6, 2, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (61, 2, 5, 4, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (62, 2, 9, 9, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (63, 2, 8, 11, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (64, 2, 10, 18, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (65, 2, 13, 21, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (66, 2, 11, 25, 2, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (67, 3, 8, 1, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (68, 3, 10, 2, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (69, 3, 5, 6, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (70, 3, 2, 8, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (71, 3, 6, 32, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (72, 3, 7, 15, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (73, 3, 11, 18, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (74, 3, 9, 22, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (75, 3, 13, 26, 2, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (76, 4, 9, 1, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (77, 4, 13, 2, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (78, 4, 8, 6, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (79, 4, 4, 8, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (80, 4, 7, 10, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (81, 4, 6, 15, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (82, 4, 5, 20, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (83, 4, 11, 22, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (84, 4, 10, 23, 2, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (85, 5, 8, 3, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (86, 5, 6, 6, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (87, 5, 5, 8, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (88, 5, 9, 11, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (89, 5, 10, 16, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (90, 5, 7, 18, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (91, 5, 11, 21, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (92, 5, 13, 27, 2, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (93, 6, 10, 3, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (94, 6, 11, 4, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (95, 6, 7, 9, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (96, 6, 9, 15, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (97, 6, 6, 21, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (98, 6, 8, 24, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (99, 6, 5, 29, 2, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (100, 7, 7, 3, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (101, 7, 11, 6, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (102, 7, 10, 11, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (103, 7, 8, 14, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (104, 7, 9, 23, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (105, 7, 6, 29, 2, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (106, 1, 5, 4, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (107, 1, 7, 9, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (108, 1, 6, 32, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (109, 1, 11, 13, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (110, 1, 10, 14, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (111, 1, 8, 22, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (112, 1, 9, 31, 3, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (113, 2, 11, 5, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (114, 2, 10, 9, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (115, 2, 5, 32, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (116, 2, 8, 13, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (117, 2, 6, 15, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (118, 2, 9, 27, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (119, 2, 7, 31, 3, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (120, 3, 6, 2, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (121, 3, 5, 5, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (122, 3, 3, 8, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (123, 3, 7, 11, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (124, 3, 9, 13, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (125, 3, 11, 25, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (126, 3, 8, 27, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (127, 3, 10, 31, 3, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (128, 4, 7, 2, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (129, 4, 1, 8, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (130, 4, 8, 10, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (131, 4, 10, 13, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (132, 4, 11, 14, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (133, 4, 9, 21, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (134, 4, 5, 26, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (135, 4, 7, 27, 3, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (136, 5, 8, 2, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (137, 5, 6, 9, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (138, 5, 10, 10, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (139, 5, 11, 12, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (140, 5, 9, 18, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (141, 5, 5, 23, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (142, 5, 7, 27, 3, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (143, 6, 9, 6, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (144, 6, 11, 14, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (145, 6, 10, 18, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (146, 6, 7, 22, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (147, 6, 6, 23, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (148, 6, 5, 28, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (149, 6, 8, 31, 3, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (150, 7, 9, 3, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (151, 7, 8, 6, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (152, 7, 5, 14, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (153, 7, 7, 23, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (154, 7, 6, 27, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (155, 7, 11, 31, 3, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (156, 1, 13, 2, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (157, 1, 8, 9, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (158, 1, 6, 32, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (159, 1, 7, 13, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (160, 1, 9, 14, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (161, 1, 11, 18, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (162, 1, 10, 22, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (163, 1, 5, 29, 4, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (164, 2, 7, 1, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (165, 2, 10, 2, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (166, 2, 5, 8, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (167, 2, 9, 10, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (168, 2, 8, 14, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (169, 2, 11, 19, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (170, 2, 13, 21, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (171, 2, 6, 29, 4, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (172, 3, 8, 1, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (173, 3, 9, 2, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (174, 3, 11, 4, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (175, 3, 7, 9, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (176, 3, 5, 32, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (177, 3, 10, 13, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (178, 3, 6, 15, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (179, 3, 13, 28, 4, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (180, 4, 9, 1, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (181, 4, 6, 2, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (182, 4, 5, 4, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (183, 4, 4, 8, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (184, 4, 7, 10, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (185, 4, 11, 13, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (186, 4, 10, 15, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (187, 4, 13, 18, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (188, 4, 8, 22, 4, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (189, 5, 6, 3, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (190, 5, 11, 5, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (191, 5, 3, 8, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (192, 5, 7, 11, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (193, 5, 9, 13, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (194, 5, 8, 15, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (195, 5, 5, 20, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (196, 5, 10, 22, 4, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (197, 6, 8, 2, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (198, 6, 5, 6, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (199, 6, 6, 9, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (200, 6, 10, 11, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (201, 6, 7, 18, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (202, 6, 9, 22, 4, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (203, 7, 10, 3, 4, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (204, 7, 7, 7, 4, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (205, 7, 6, 20, 4, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (206, 7, 9, 21, 4, 7);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (207, 1, 6, 2, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (208, 1, 5, 8, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (209, 1, 8, 11, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (210, 1, 10, 14, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (211, 1, 7, 17, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (212, 1, 11, 23, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (213, 1, 9, 31, 5, 1);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (214, 2, 7, 2, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (215, 2, 10, 6, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (216, 2, 9, 9, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (217, 2, 6, 32, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (218, 2, 11, 15, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (219, 2, 5, 17, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (220, 2, 8, 31, 5, 2);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (221, 3, 8, 3, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (222, 3, 6, 7, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (223, 3, 7, 9, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (224, 3, 5, 32, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (225, 3, 9, 33, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (226, 3, 10, 24, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (227, 3, 11, 31, 5, 3);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (228, 4, 9, 3, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (229, 4, 5, 5, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (230, 4, 11, 9, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (231, 4, 7, 10, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (232, 4, 10, 16, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (233, 4, 8, 17, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (234, 4, 6, 23, 5, 4);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (235, 5, 10, 9, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (236, 5, 9, 11, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (237, 5, 11, 14, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (238, 5, 6, 17, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (239, 5, 8, 21, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (240, 5, 5, 23, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (241, 5, 7, 31, 5, 5);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (242, 6, 5, 7, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (243, 6, 6, 9, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (244, 6, 7, 14, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (245, 6, 9, 17, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (246, 6, 11, 21, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (247, 6, 8, 23, 5, 6);
INSERT INTO SCHEDULE (id, lesson_number, class_id, teacher_subject_id, day_of_week_id, lesson_time_id) VALUES (248, 6, 10, 31, 5, 6);
